name: simple-whitenoise-for-babies CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.14.1'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Build Application
        run: npm run build -- --base=/${{ github.event.repository.name }}/
      
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.9.2
        with:
          publish_dir: ./dist
          github_token: ${{ secrets.GITHUB_TOKEN }}  
